# Generated by Django 3.0.3 on 2020-02-04 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_parent', to='tree.Node', verbose_name='Родитель')),
            ],
        ),
        migrations.CreateModel(
            name='TreePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_ancestor', to='tree.Node', verbose_name='Предок')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_descendant', to='tree.Node', verbose_name='Потомок')),
            ],
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
    ]
