# Generated by Django 3.0.3 on 2020-02-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20200204_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treepath',
            name='ancestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_ancestor', to='tree.Node', verbose_name='Предок'),
        ),
    ]
